@extends('client.share.master')
@section('noi_dung')
    @include('client.banner')
    @include('client.ship')
    @include('client.san_pham_show')
    @include('client.slide')
    @include('client.best_sale')
@endsection
@section('js')
@endsection
